### ISSUE TITLE
=games-engines/openmw-0.37.0 deps

### ISSUE THREAD

**Issue by init6** [hasufell/games-overlay#47]
[About new deps...](https://wiki.openmw.org/index.php?title=Development_Environment_Setup_OSG)

So now:

	# cat games-engines-openmw-0.37.0-games-overlay.patch
	diff -Naur a/games-engines/openmw/openmw-0.37.0.ebuild b/games-engines/openmw/openmw-0.37.0.ebuild
	--- a/games-engines/openmw/openmw-0.37.0.ebuild	2015-12-05 15:20:52.000000000 +0500
	+++ b/games-engines/openmw/openmw-0.37.0.ebuild	2015-12-06 10:19:35.932464844 +0500
	@@ -12,26 +12,26 @@
	
	LICENSE="GPL-3 MIT BitstreamVera OFL-1.1"
	SLOT="0"
	-KEYWORDS="~amd64 ~x86"
	+KEYWORDS="amd64 x86"
	IUSE="doc devtools"
	
	# XXX static build
	RDEPEND="
		app-arch/unshield
	-	>=dev-games/mygui-3.2.1[ogre]
	-	>=dev-games/ogre-1.9.0[-double-precision,freeimage,ois,opengl,zip]
	+	>=dev-games/mygui-3.2.1[-opengl,-ogre]
		dev-games/openscenegraph[jpeg,png,qt4]
		>=dev-libs/boost-1.46.0
		dev-libs/tinyxml
		>=dev-qt/qtcore-4.7.0:4
		>=dev-qt/qtgui-4.7.0:4
		media-libs/freeimage[png,jpeg] # Looks like now not need?
	-	media-libs/freetype:2
		media-libs/libsdl2[X,video]
		media-libs/openal
		>=sci-physics/bullet-2.80
		virtual/ffmpeg
	-	devtools? ( dev-qt/qtxmlpatterns:4 )"
	+	devtools? ( dev-qt/qtxmlpatterns:4 )
	+	media-libs/libtxc_dxtn # <-- this deps need only on nouveau and other opensource video drivers. More? Read https://wiki.openmw.org/index.php?title=Development_Environment_Setup_OSG
	+	"
	DEPEND="${RDEPEND}
		virtual/pkgconfig
		doc? ( app-doc/doxygen media-gfx/graphviz )"
	@@ -51,6 +51,7 @@
			-DOPENMW_RESOURCE_FILES="/usr/share/${PN}/resources"
			-DGLOBAL_CONFIG_PATH="/etc"
			-DUSE_SYSTEM_TINYXML=ON
	+		-DCMAKE_BUILD_TYPE=Release # Why not Release?
		)
	
		cmake-utils_src_configure

**Comment by hasufell** [comment]
* `-ogre` for mygui is not correct (not having `ogre` USE flag and `-ogre` are not the same)
* optional dependencies like `media-libs/libtxc_dxtn` should be printed in pkg_postinst, not added to RDEPEND
* `-DCMAKE_BUILD_TYPE=Release` is discouraged, since it will overwrite our build type that ensures correct CFLAGS
* although freetype doesn't end up in DT_NEEDED, it's explicitly used in the build system for linking mygui and I think it's fine to keep it that way

So the change should rather be something like:
```sh
-   >=dev-games/mygui-3.2.1[ogre]
-   >=dev-games/ogre-1.9.0[-double-precision,freeimage,ois,opengl,zip]
+   >=dev-games/mygui-3.2.1
```
