### ISSUE TITLE
games-strategy/0ad should force rebuild of data on emerge @preserved-rebuild

### ISSUE THREAD

**Issue by velnias75** [hasufell/games-overlay#5]
I had following scenario today:

I've upgraded *boost* which resulted in a `emerge @preserved-rebuild` hint. Ok, I did that and my formerly from the *gentoo repo* installed **0ad** got rebuild nice and cleanly from *games-overlay*. So far so good. Starting **0ad** yielded in error messages about the data. :anguished: 
The data is located somewhere else in a install from *gentoo repo*, thus it cannot find it! :angry:

**Comment by hasufell** [comment]
This is unrelated to ```@preserved-rebuild```, because 0ad-data does not have any libraries.

The reason for this bug is that my overlay voluntarily conflicts with the gentoo tree, because I do not use the games.eclass hacks.

There are more potential packages that will cause trouble, e.g. renpy and eselect-renpy if they are mixed from both repositories.

None of these issues will ever occur if you had no games installed prior to installing this overlay (because overlays naturally have a higher priority than the base tree). I could probably add a note on how to fix these kind of problems, e.g. by reinstalling all installed packages that have been installed from ```::gentoo```, but are also present in ```::games-overlay```. I'll see if I can come up with a command for that.

**Comment by hasufell** [comment]
```emerge -av1 $(eix --only-names --installed-from-overlay gentoo --in-overlay games-overlay)```

**Comment by hasufell** [comment]
Additionally you can fix compatibility by adding this to your make.conf
```
GAMES_PREFIX=/usr
GAMES_PREFIX_OPT=/opt
GAMES_DATADIR=/usr/share
GAMES_DATADIR_BASE=/usr/share
GAMES_SYSCONFDIR=/etc
GAMES_STATEDIR=/var/lib
GAMES_LOGDIR=/var/log
GAMES_BINDIR=${GAMES_PREFIX}/bin
GAMES_GROUP=users
```

**Comment by hasufell** [comment]
9f750006ceaa8b311bdde3094b6a93d5f0a5f30f
